services:
  - type: web
    name: hamad700
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    staticPublishPath: staticfiles
    pythonVersion: 3.11
