# Generated by Django 5.2.3 on 2025-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='الصورة',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_images/', verbose_name='صورة المهمة'),
        ),
        migrations.AddField(
            model_name='task',
            name='العنوان',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المهمة'),
        ),
        migrations.AddField(
            model_name='task',
            name='الوصف',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المهمة'),
        ),
        migrations.AddField(
            model_name='task',
            name='مكتملة',
            field=models.BooleanField(default=False, verbose_name='هل اكتملت؟'),
        ),
    ]
