# Generated by Django 5.2.3 on 2025-06-21 18:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_at_remove_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='الصورة',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة المهمة'),
        ),
    ]
